---
title: "Ohjelmistoymparisto"
---

Kurssilla käytettävät ohjelmistot ovat poikkeuksetta [vapaita](https://fi.wikipedia.org/wiki/Vapaa_ohjelmisto) ja [avoimen lähdekoodin ohjelmistoja](https://fi.wikipedia.org/wiki/Avoin_l%C3%A4hdekoodi), joita voi käyttää sekä Windowsissa, OSX:ssä että eri linux-jakeluissa.


# Ohjelmistot

Ohjelmistoympäristö on perusteltu ja käyty läpi hyvin täällä: [Jenny Bryan and the STAT 545 TAs: Happy Git and GitHub for the useR](http://happygitwithr.com/)

## R




## R Studio

- RStudio Full Tour <https://vimeo.com/97378167>

## Rmarkdown

- What is R Markdown? <https://vimeo.com/177254549>
- Communicate-better-with-R-Markdown  <https://vimeo.com/176881928>
- Getting started with R Markdown  <https://vimeo.com/142172484>

## git

- git <https://git-scm.com/>
- The Basics of Git and GitHub <https://www.youtube.com/watch?v=U8GBXvdmHT4>
- Lear Git in 20 minutes <https://www.youtube.com/watch?v=Y9XZQO1n_7c>
- RStudio & git/github Demonstration <https://vimeo.com/119403806>


## shell

- Shell script <https://en.wikipedia.org/wiki/Shell_script>

## Github-koodinjakopalvelu

[Github](https://github.com) ei ole ohjelmisto, vaan kenties suosituin lähdekoodin jakamisen ja yhdessä ohjelmoimisen (social coding) mahdollistava verkkopalvelu. Kurssille osallistuminen edellyttää Github:iin rekisteröitymistä.

# Ympäristöt

## Pilvessä

Kurssin ensisijainen laskentaympäristö on [Tieteen tietotekniikan keskuksen (CSC)](http://csc,fi) *Pouta Blueprints* palvelimilla, joita opiskelijat voivat käyttää haka-verkon kautta pelkkää selainta käyttöen joko mikroluokkien koneilla tai omalla koneella.


# Paikalliset asennukset omille koneille

Kurssin edetessä
